### ISSUE TITLE
Components Library: Label Component

### ISSUE THREAD

**Issue by vlatawiec** [EQWorks/lumen-labs#110]
# 🎯 Usage 
- Labels are used to display content classification to users. These UI elements are often used when filtering and/or displaying search and analysis results, and generally to provide content information to users. When used with a “delete” icon, these labels can be removed, by the user.

# 🎭  Types
- **Outlined**: Labels can either have an outline, or not (by default). Outline sizes increase as label size increases. Outlines also vary in colour, based on the colour of the label used. 
![Outlined](https://user-images.githubusercontent.com/79470291/157321914-01f7c4f8-ba6c-4d5e-8493-e094a1ab9535.png)
- **Text Type**: To accommodate additional use cases, labels are designed with both default text (single, bold line of text) and “with title” text (double, primary bolded, secondary regular lines of text). These differences in text are accompanied by different padding and sizing.
![Text_Type](https://user-images.githubusercontent.com/79470291/157322019-db08d96f-02ae-489f-b2f3-92a2c7c91ded.png)
-  **Stylization for Use Case**: Labels can be stylized in different ways depending on use case. Both primary and secondary icons are optional, and can be changed depending on purpose of label. 
![Stylization](https://user-images.githubusercontent.com/79470291/157322044-7f7d750f-1c22-475d-bbc2-dd2a560cf80e.png)
-  **Shades**: Labels come in two different shades (Light & Dark), with the same five base colours (Blue, Grey, Success, Warning, Error). Light Labels are the primary use case, and should be used in most instances. Dark Labels were created for potential UI expansion, and do not currently have a use case, but may be used if stylistically necessary.

# 🫀 Anatomy
![Anatomy](https://user-images.githubusercontent.com/79470291/157323353-5dee60e6-07d7-4a81-a02e-9ac2c1fcd0a6.png)

**Spacing, Sizing & Alignment:**
- Since labels are often stacked, or used together, it is important to leave an equal margin between tag components, other components (tag, or otherwise) and their containers. Appropriate spacing varies per use case, but in general should be no less than 8px in width and/or height from other UI elements, or other labels when stacked.
- There are three sizes for labels - small, medium, and large. These sizes have fixed heights, and wrap around label content, meaning the width can vary. Elements within labels are centre-aligned with fixed padding.
- **Small**: height: 16px;  font-size: 10pt;  icon-size: 10x10px;
![Small_Anatomy](https://user-images.githubusercontent.com/79470291/157324178-70b21ed0-e57d-4b7d-b094-3f8f523946e0.png)
- **Medium**: height: 20px;  font-size: 12pt;  icon-size: 12x12px;
![Medium_Anatomy](https://user-images.githubusercontent.com/79470291/157324318-07c255dd-8397-49f3-a7fc-78d7e2fb2a77.png)
- **Large**: height: 24px;  font-size: 14pt;  icon-size: 14x14px; 
![Large_Anatomy](https://user-images.githubusercontent.com/79470291/157324455-df3f9cd9-671b-40d2-a4ca-aa6a6486c877.png)

# 💟 Icons Used
- [Hash](https://app.streamlinehq.com/icons/streamline-bold/interface-essential/text-formating/hash)
- [Database_Search](https://app.streamlinehq.com/icons/streamline-bold/programing-apps-websites/databases/database-search)
- [Information_Circle](https://app.streamlinehq.com/icons/streamline-bold/interface-essential/alerts/information-circle)
- [Earth](https://app.streamlinehq.com/icons/streamline-bold/maps-navigation/earth/earth-1)
- [Remove](https://app.streamlinehq.com/icons/streamline-bold/interface-essential/remove-add/remove)

# 🔗 Zeplin Link
- [Labels](https://zpl.io/nolzevx)

# 🔢  Attributes(TBD/WIP)
Property | Type | Default Value | Description
--- | --- | --- | ---
`attribute_name` | `type` | `'default_val'` | Description of the attribute

# 🔍 Design Preview
![Labels](https://user-images.githubusercontent.com/79470291/157323057-87537dd0-1ad7-4193-b6a5-334ff123d351.png)

**Comment by sallkall** [comment]
This replaces the previous [chip](https://github.com/EQWorks/lumen-labs/issues/15) component
