### ISSUE TITLE
Skeleton Loader  - Alternate Designs

### ISSUE THREAD

**Issue by Hamaad102** [EQWorks/lumen-labs#155]
Future revisions of snoke-dashboard will add three new types of graphs: Barline, Line and Pyramid

We need designs of these three to incorporate into the component.

**Comment by vlatawiec** [comment]
FIGMA design file is updated to reflect new Assets (Line, Pyramid, BarLine). Assets have been created as components, and all size/breakpoint block versions have been added. @Hamaad102 this is "complete" (unless you have any other tasks needed!) from a design side. Let me know if you have any questions/concerns etc. Thanks! 

Reference: https://www.figma.com/file/RB5JLQk54JgzUK6a50ej7S/COX-Dashboard?node-id=4434%3A124050&t=fP9L4fY70QgEWnQm-3

**Comment by Hamaad102** [comment]
> https://www.figma.com/file/RB5JLQk54JgzUK6a50ej7S/COX-Dashboard?node-id=4434%3A124050&t=fP9L4fY70QgEWnQm-3

Thank you for getting this done so quick! I don't think there are any other requirements at the moment so we should be good.
